### ISSUE TITLE
Bug:  Escape charactersd dose not works 

### ISSUE THREAD

**Issue by redcatsec** [jacek-kurlit/pik#65] opened 2024-09-18 07:28 UTC
When I try to escape characters from the search bar, I get the character `h` instead of removing the character.
I am using Kali and the latest stable versions of Rust and Cargo.
<img width="521" alt="Screenshot 2024-09-18 at 09 22 02" src="https://github.com/user-attachments/assets/94f7553c-a75a-4abc-963f-6b655032101b">

**Comment by jacek-kurlit** [comment] 2024-09-18 08:09
Hi,
I'm not sure if char escape will work out of the box.
Can you describe your use case?
What exactly you have typed and what result you are expecting to see?

**Comment by jacek-kurlit** [comment] 2024-09-24 08:16
Closing due to being unable to reproduce (fedora with wezterm terminal).
Feel free to reopen if you can provide any feedback

**Closed by jacek-kurlit** 2024-09-24 08:16 UTC
Labels: bug
